# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default=b'level', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.CharField(default=b'prereqs', max_length=200),
        ),
    ]
